[db]
host = "localhost"   # env DB_HOST
port = 3306          # env DB_PORT
database = ""        # env DB_DATABASE
username = ""        # env DB_USERNAME  Should have only read access!
password = ""        # env DB_PASSWORD
log_queries = false

[logger]
level = "DEBUG"
file = "./logs/flare-indexer.log"
console = false

[services]
address = "0.0.0.0:8000"  # address to listen on

[chain]
address_hrp = "flare"
chain_id = 14
# node rpc url, e.g.,
# http://xxx.xx.xxx.xxx:xxxx/ext/C/rpc; env ETH_RPC_URL;
eth_rpc_url = "node rpc address"
api_key = ""  # from env API_KEY (if neede to access the node rpc)

[contract_addresses]
voting = "0x12b3079D5b65a17EFD1665d9731FB0Adb46F14e4"  # env VOTING_CONTRACT_ADDRESS
